indirimhaber/indirimhaber/Controllers/HaberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace indirimhaber.Controllers
{
    public class HaberController : Controller
    {
        
        FırsatHaberleriEntities db = new FırsatHaberleriEntities();
        public ActionResult Index()
        {
            ViewBag.Kategoriler = new SelectList(db.Kategori.ToList(),"ID","KategoriAd");
            var model = db.Haber.ToList();
            return View(model);


        }
        
        
            
        [HttpPost]    
        public ActionResult Index(Models.HaberAramaModel arama)
        {
            //Arama Yaparken kullanılıyor.
            //Textbox içindekiyle HaberBasliklar karşılaştırılır.
            //Armaa Çalışmıyor.
            var sorgu = db.Haber.AsQueryable();
            if(!string.IsNullOrEmpty(arama.HaberBaslik))
            {
                sorgu = sorgu.Where(x => x.HaberBaslik.Contains(arama.HaberBaslik));
            }
            if(arama.Kategoriler>0)
            {
                sorgu = sorgu.Where(x => x.FKKategoriID == arama.Kategoriler);
            }
            //Kategoriler DropdownList Doldurur.
            ViewBag.Kategoriler = new SelectList(db.Kategori.ToList(), "ID", "KategoriAd");
            var model = sorgu.ToList();
            return View(model);
        }

        public ActionResult Detay(int id)
        {
            var model = db.Haber.Find(id);
            return View(model);
        }

        public ActionResult Olustur()
        {
            ViewBag.FKKategoriID = new SelectList(db.Kategori.ToList(), "ID", "KategoriAd");
            return View();
        }

        
        [HttpPost]
        public ActionResult Olustur(Haber model)
        {
            
            //   model.EklenmeTarihi = DateTime.Now();   Eklenme Tarihi Otomatik olarak atanır.
            if (ModelState.IsValid)
            {
                db.Haber.Add(model);
                db.SaveChanges();

            }
            return RedirectToAction("Index");
        }
        
        //Haber/Duzenle/1 
        
        public ActionResult Duzenle(int id)
        {
            ViewBag.FKKategoriID = new SelectList(db.Kategori.ToList(), "ID", "KategoriAd");

            var model = db.Haber.Find(id);
            return View(model);
        }


        [HttpPost]
        public ActionResult Duzenle(Haber model)
        {

            if(ModelState.IsValid)
            {
                var kayit = db.Haber.Find(model.ID);
                TryUpdateModel(kayit);
                db.SaveChanges();
                ViewBag.KayitBasarili = true;
            }
            else
            {
                ViewBag.KayitBasarili = false;
            }
            ViewBag.FKKategoriID = new SelectList(db.Kategori.ToList(), "ID", "KategoriAd");
            return View();
        }
        
        public ActionResult Sil(int id)
        {
            var model = db.Haber.Find(id);
            return View();
        }
        
        [HttpPost]
        public ActionResult SilOnay(int id)
        {

            if(ModelState.IsValid)
            {
                var model = db.Haber.Find(id);
                db.Haber.Remove(model);
                db.SaveChanges();

            }

            return RedirectToAction("Index");
        }
    }
}

indirimhaber/indirimhaber/Views/Haber/Detay.cshtml
@model indirimhaber.Haber

@{
    ViewBag.Title = "Detay";
}
<div class="panel panel-success">
    <h2>@Html.DisplayFor(m => m.HaberBaslik)</h2>


    <div>
        <!-- Kategori Haber Detay gibi bilgileri çekiyoruz.-->
        <h4>@Html.DisplayFor(m => m.HaberDetay)</h4>
        <span class="label label-primary">@Model.Kategori.KategoriAd</span>
        <hr />
        <h4>Haberimizin Detayları Aşağıdadır.</h4>
        @Model.Habericerik
    </div>
</div>
<p>
    @Html.ActionLink("Düzenle", "Duzenle", new { id = Model.ID }) |
    @Html.ActionLink("Listeye Geri Dön", "Index")
    @Html.ActionLink("Kaydı Sil", "Sil", new { id = Model.ID })
    
</p>

indirimhaber/indirimhaber/Views/Haber/Duzenle.cshtml
@model indirimhaber.Haber

@{
    ViewBag.Title = "Duzenle";
}

<h2>Duzenle</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Haber</h4>
        <hr />

        @if (ViewBag.KayitBasarili != null && ViewBag.KayitBasarili)
        {
            <h3>Kayıt işlemi başarıyla gerçekleştirildi.</h3>
        }
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.HaberBaslik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HaberBaslik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HaberBaslik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HaberDetay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HaberDetay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HaberDetay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">

            @Html.LabelFor(model => model.EklenmeTarihi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EklenmeTarihi, new { htmlAttributes = new { @class = "form-control", placeholder = DateTime.Now } })
                @Html.ValidationMessageFor(model => model.EklenmeTarihi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FKKategoriID, "FKKategoriID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FKKategoriID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FKKategoriID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Habericerik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Habericerik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Habericerik, "", new { @class = "text-danger" })
            </div>
        </div>

        @section scripts{
        <script src="//cdn.ckeditor.com/4.6.1/basic/ckeditor.js"></script>
        <script>
            CKEDITOR.replace( 'Habericerik' );
        </script>
        }

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Yeni Haber Ekle" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

indirimhaber/indirimhaber/Views/Haber/Index.cshtml
@model List<Haber>
@{
    ViewBag.Title = "Haber Listesi";
}

<h2>Tüm Haberler</h2>
<!-- Arama-->

 @using (Html.BeginForm())
 {
    <input tpye="text" class="form-control" id="haberAdi" name="HaberArama" placeholder="Haber Arama" />
    @Html.DropDownList("Kategoriler","Bir Kategori Seciniz")
    <input class="btn btn-default" type="submit" value="ARA" />
 }

<table class="table table-hover">
    <thead>
        <tr>
            <th>Haber Baslik</th>
            <th>Haber Detay</th>
            <th>Eklenme Tarihi</th>
            <th>Kategori</th>
        </tr>
    </thead>
    <tbody>
        <!--Başka tabloya joinlemiş olduk.-->
            @foreach (var item in Model)
            {
                <tr>
                    <td>"@item.HaberBaslik</td>
                    <td>@item.HaberDetay</td>
                    <td><@item.EklenmeTarihi</td>
                    <td><span class="label label-primary">@item.Kategori.KategoriAd</span></td>
                    <td><a class="btn btn-success" href="@Url.Action("Detay", "Haber", new { id = item.ID }) ">Haberin Ayrıntıları</a> </td>
                </tr>
                }
    </tbody>
</table>

indirimhaber/indirimhaber/Views/Haber/Olustur.cshtml
@model indirimhaber.Haber

@{
    ViewBag.Title = "Olustur";
}

<h2>Olustur</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">  
        <h4>Haber</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.HaberBaslik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HaberBaslik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HaberBaslik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HaberDetay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HaberDetay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HaberDetay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
           
            @Html.LabelFor(model => model.EklenmeTarihi, htmlAttributes: new { @class = "control-label col-md-2"  })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EklenmeTarihi, new { htmlAttributes = new { @class = "form-control",placeholder=DateTime.Now } })
                @Html.ValidationMessageFor(model => model.EklenmeTarihi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FKKategoriID, "FKKategoriID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FKKategoriID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FKKategoriID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Habericerik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Habericerik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Habericerik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Yeni Haber Ekle" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

indirimhaber/indirimhaber/Views/Haber/Sil.cshtml
@model indirimhaber.Haber

@{
    ViewBag.Title = "Sil";
}

<h2>Sil</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Haber</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.HaberBaslik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HaberBaslik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HaberDetay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HaberDetay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EklenmeTarihi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EklenmeTarihi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Habericerik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Habericerik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Kategori.KategoriAd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kategori.KategoriAd)
        </dd>

    </dl>

    @using (Html.BeginForm("SilOnay","Haber",FormMethod.Post)) {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(m => m.ID);
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>